spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

app:
  web:
    url: ${APP_WEB_URL}
  telegram:
    management:
      enabled: true
      connection-mode: ${APP_TELEGRAM_MANAGEMENT_CONNECTION_MODE:LONG_POLLING}
      token: ${APP_TELEGRAM_MANAGEMENT_TOKEN}
      username: ${APP_TELEGRAM_MANAGEMENT_USERNAME}
