
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        show_sql: true




bot:
  token: 7713894529:AAGgcwHtYi6uv38Z2T7KIMRTEKVjsoRbkz4
  username: bott_forge_bot

